### ISSUE TITLE
添加回声洞收藏与已读功能

### ISSUE THREAD

**Issue by haitang000** [wling-art/U1bot#129]
# 已读功能说明
回复回声洞消息，输入「已读」即可。已读后的回声洞将不会再次推送给用户

**Comment by haitang000** [comment]
补充:已读后的回声洞可以通过某个命令再次取消已读

**Comment by haitang000** [comment]
> 这会产生一个问题就是万一全部读完了呢

你其实可以设置上限的

**Comment by wling-art** [comment]
没必要，因为回声洞是需要随机性的，不管重复不重复了
