### ISSUE TITLE
添加 一键卖鱼、估价 系统

### ISSUE THREAD

**Issue by haitang000** [wling-art/U1bot#138]
### 一键卖鱼
使用 "一键卖鱼 全部" 将**背包中的所有鱼**卖掉，在卖鱼之前需要用户确定以防止误触

### 一键卖鱼 <品质>
使用 "一键卖鱼 <品质>" 卖出**背包内对应品质的所有鱼**，在卖鱼之前同样需要用户确定以防止误触

### 估价
使用 "估价 <品质>/<鱼的名称>" 对背包中的所有对应品质或名称的鱼进行估价

**Comment by wling-art** [comment]
我认为不需要确认，居然都发出去，不会有人误触的
